server:
  port: 8532

spring:
  application:
    name: producer-server02
  cloud:
    # 注册中心 consul服务的ip和端口号
    consul:
      host: 127.0.0.1
      port: 8500
      # 服务名称
      discovery:
        service-name: service-producer
        # 心跳检测
        heartbeat:
          enabled: true
        enabled: true
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    # 注册中心结束



