server:
  port: 8550
spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          uri: github.com
          username: clear
          password: 123456
